Repository element-hq/synapse, pull requests merged in 2024-11, with the labels that each got.

#17809 Sliding Sync: Lazy-loading room members on incremental sync (remember memberships)
  changelog.d/17809.bugfix
  synapse/handlers/sliding_sync/__init__.py
  tests/handlers/test_sliding_sync.py
  tests/rest/client/sliding_sync/test_rooms_required_state.py
Labels: A-Sync

#17888 Add experimental support for MSC4222
  changelog.d/17888.feature
  docs/admin_api/experimental_features.md
  synapse/config/experimental.py
  synapse/handlers/sync.py
  synapse/rest/admin/experimental_features.py
  synapse/rest/client/sync.py
  tests/handlers/test_sync.py
Labels: A-Sync

#17946 Speed up slow initial sliding syncs on large servers
  changelog.d/17946.misc
  synapse/_scripts/synapse_port_db.py
  synapse/storage/databases/main/sliding_sync.py
  synapse/storage/schema/main/delta/88/05_sliding_sync_room_config_index.sql
Labels: X-Release-Blocker

#17932 Support both import names of PyPI package `python-multipart`.
  changelog.d/17932.misc
  synapse/http/client.py
Labels: X-Release-Blocker

#17889 Enable authenticated media by default
  changelog.d/17889.feature
  docs/upgrade.md
  docs/usage/configuration/config_documentation.md
  synapse/config/repository.py
  tests/media/test_media_storage.py
  tests/replication/test_multi_media_repo.py
  tests/rest/admin/test_admin.py
  tests/rest/admin/test_media.py
  tests/rest/admin/test_user.py
  tests/rest/media/test_domain_blocking.py
  tests/rest/media/test_url_preview.py
Labels: X-Release-Blocker

#17960 Fix `delete_old_otks` job on worker deployments
  changelog.d/17960.bugfix
  synapse/server.py
Labels: X-Release-Blocker

#17972 Consolidate SSO redirects through `/_matrix/client/v3/login/sso/redirect(/{idpId})`
  changelog.d/17972.misc
  synapse/api/urls.py
  synapse/config/cas.py
  synapse/config/server.py
  synapse/rest/synapse/client/pick_idp.py
  tests/api/test_urls.py
  tests/rest/client/test_login.py
  tests/rest/client/utils.py
Labels: A-SSO
