Repository element-hq/synapse, pull requests merged in 2025-02, with the labels that each got.

#18004 Add MSC3861 config options admin_token_path and client_secret_path
  changelog.d/18004.feature
  synapse/api/auth/msc3861_delegated.py
  synapse/config/experimental.py
  tests/config/test_load.py
  tests/handlers/test_oauth_delegation.py
Labels: A-Config

#18145 Add `rc_presence` ratelimiting config to demo/start.sh
  changelog.d/18145.bugfix
  demo/start.sh
Labels: A-Presence

#18158 Add support to proxy outbound requests from Synapse in tests
  changelog.d/18158.docker
  docker/README.md
  docker/conf-workers/synapse.supervisord.conf.j2
  docker/configure_workers_and_start.py
  synapse/http/proxyagent.py
Labels: A-Testing
