Repository element-hq/synapse, pull requests merged in 2025-08, with the labels that each got.

#18733 Update metrics linting to be able to handle custom metrics
  changelog.d/18733.misc
  mypy.ini
  scripts-dev/mypy_synapse_plugin.py
  synapse/metrics/__init__.py
  synapse/metrics/_gc.py
  synapse/metrics/_reactor_metrics.py
  synapse/metrics/background_process_metrics.py
  synapse/metrics/jemalloc.py
  synapse/util/caches/__init__.py
  tests/metrics/test_metrics.py
Labels: A-Metrics

#18574 Make room upgrades faster for rooms with many bans
  changelog.d/18574.misc
  synapse/handlers/message.py
  synapse/handlers/room.py
  synapse/storage/databases/main/roommember.py
  tests/rest/client/test_upgrade_room.py
Labels: A-Room-Upgrades, A-Membership

#18751 Fix `LaterGauge` metrics to collect from all servers
  changelog.d/18751.misc
  synapse/federation/send_queue.py
  synapse/federation/sender/__init__.py
  synapse/handlers/presence.py
  synapse/http/request_metrics.py
  synapse/metrics/__init__.py
  synapse/notifier.py
  synapse/replication/tcp/handler.py
  synapse/replication/tcp/protocol.py
  synapse/storage/database.py
  synapse/storage/databases/main/roommember.py
  synapse/util/ratelimitutils.py
  synapse/util/task_scheduler.py
  tests/metrics/test_metrics.py
Labels: A-Metrics

#18756 Update implementation of MSC4306: Thread Subscriptions to include automatic subscription conflict prevention as introduced in later drafts.
  changelog.d/18756.misc
  synapse/api/errors.py
  synapse/handlers/thread_subscriptions.py
  synapse/replication/tcp/streams/_base.py
  synapse/rest/client/thread_subscriptions.py
  synapse/storage/databases/main/thread_subscriptions.py
  synapse/storage/schema/main/delta/92/09_thread_subscriptions_update.sql
  synapse/storage/schema/main/delta/92/09_thread_subscriptions_update.sql.postgres
  synapse/types/__init__.py
  synapse/util/pydantic_models.py
  tests/replication/tcp/streams/test_thread_subscriptions.py
  tests/rest/client/test_thread_subscriptions.py
  tests/rest/client/utils.py
  tests/storage/test_thread_subscriptions.py
Labels: A-Threads

#18762 Implement the push rules for experimental MSC4306: Thread Subscriptions.
  changelog.d/18762.feature
  rust/benches/evaluator.rs
  rust/src/push/base_rules.rs
  rust/src/push/evaluator.rs
  rust/src/push/mod.rs
  synapse/push/bulk_push_rule_evaluator.py
  synapse/storage/databases/main/push_rule.py
  synapse/storage/databases/main/thread_subscriptions.py
  synapse/synapse_rust/push.pyi
  tests/push/test_bulk_push_rule_evaluator.py
  tests/push/test_push_rule_evaluator.py
  tests/storage/test_thread_subscriptions.py
Labels: A-Threads

#18780 register_new_matrix_user: Fix error message for registration shared secret
  changelog.d/18780.bugfix
  synapse/_scripts/register_new_matrix_user.py
Labels: A-Config

#18805 Make the Make Room Admin API choose to puppet the room creator in v12 rooms
  changelog.d/18805.bugfix
  synapse/rest/admin/rooms.py
  tests/rest/admin/test_room.py
Labels: X-Release-Blocker
